version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: reto_2_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    volumes: 
      - ./db_data:/data/db
    ports:
      - 27016:27017
    